version: "3.9"
services:

# Core Services
  api:
    image: satellite-task-selector
    container_name: task-selector
    build:
      context: .
    ports:
      - "8080:80"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - LOGGER_LEVEL=DEBUG
    depends_on:
      - redis
    volumes:
      - logs-data:/logs

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
        - redis_data:/data

# Monitoring
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    user: "472"
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./monitoring/datasource.yml:/etc/grafana/provisioning/datasource.yml
    env_file:
      - ./monitoring/config.monitoring

# Logging
  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    volumes:
      - elk-data:/var/lib/elasticsearch

  filebeat:
      build:
          context: ./logging/
      container_name: filebeat
      volumes:
          - logs-data:/logs
      depends_on:
          - elk
  
volumes:
    redis_data:
    elk-data:
    logs-data: 