version: "3.9"
services:
  api:
    image: satellite-task-selector
    container_name: task-selector
    build:
      context: .
    ports:
      - "8080:80"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - LOGGER_LEVEL=DEBUG
    depends_on:
      - redis
    volumes:
      - ./feedback:/src/feedback
      - ./uploads:/src/static/uploads

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
        - redis_data:/data

volumes:
    redis_data: