name: "api-filebeat"
logging.metrics.enabled: false
xpack.security.enabled: false
xpack.monitoring.enabled: false
setup.ilm.enabled: false
setup.template.enabled: false

filebeat.inputs:
- type: log
  scan_frequency: 1s
  enabled: true
  paths:
    - /logs/api.*
  fields:
    - service: api
  fields_under_root: true

output.elasticsearch:
  hosts: ["elk:9200"]
  index: "api"